export const issueType = {
	DEPOSIT: 'DEPOSIT',
	MAINTENANCE: 'MAINTENANCE',
	RENT: 'RENT',
	UTILITIES: 'UTILITIES',
	CHANGE_OF_OCCUPANCY: 'CHANGE_OF_OCCUPANCY',
	END_OF_TENANCY: 'END_OF_TENANCY',
	RENEWALS: 'RENEWALS',
	OTHER: 'OTHER'
};
