export const update_types = {
   FOXTONS_COMMENT: 'FOXTONS_COMMENT',
   INTERNAL_COMMENT: 'INTERNAL_COMMENT',
   TENANT_COMMENT: 'TENANT_COMMENT',
   LANDLORD_COMMENT: 'LANDLORD_COMMENT',
   REQUEST_QUOTE: 'REQUEST_QUOTE',
   WAITING_FOR_LANDLORD: 'WAITING_FOR_LANDLORD',
   APPOINTMENT_MADE: 'APPOINTMENT_MADE',
   RE_OPEN: 'RE_OPEN',
   CLOSE: 'CLOSE',
   CHASED_LANDLORD: 'CHASED_LANDLORD',
   APPOINTMENT_COMPLETE: 'APPOINTMENT_COMPLETE',
   AWAITING_PARTS: 'AWAITING_PARTS'
};

export const issues_statuses = {
  IN_PROGRESS: 'INP',
  LANDLORD_DEALING_WITH: 'LDW',
  NO_ACTION: 'NOA',
  OPEN: 'OPN',
  RESOLVED: 'RSV'
};
